### PR TITLE
Add more secrets manager operations

### PR DESCRIPTION
**Pull request by jordanclark**
Small change to add additional secrets manager operations: createSecret, deleteSecret, restoreSecret, getRandomPassword

### CODE REVIEW

**Comment by jordanclark** [comment]
Added all params to createSecret and added updateSecret and putSecretValue

**Comment by jcberquist** [comment]
Are you ready to have this PR merged? Also, I believe `createGUID()` is a Lucee only function - could you switch it to `createUUID()`?

**Comment by jordanclark** [comment]
@jcberquist good catch on createGUID() I replaced it as suggested.

The PR additions are ready to go.

**Comment by jcberquist** [comment]
Thank you!

**Pull request merged**
