### PR TITLE
Add basic support for KMS (encrypt/decrypt/re-encrypt)

### PR DESCRIPTION
**Pull request by barronbud**

### CODE REVIEW

**Comment by jcberquist** [comment]
@barronbud: Thank you very much for this. I am happy to merge it as is, but I would like to remove the `toJSON()` method  and just use `serializeJSON()` directly since the work it does is really dynamodb specific. Do you want to remove that, or shall I just do it after merging?

**Comment by barronbud** [comment]
@jcberquist I’ll push a new commit removing that method in favor of native. Should be sometime tomorrow.

**Comment by barronbud** [comment]
@jcberquist My recent updates look good?

**Comment by jcberquist** [comment]
Looks good, thank you!

**Pull request merged**
