### PR TITLE
add ec2 DescribeInstances #56

### PR DESCRIPTION
**Pull request by zspitzer**

### CODE REVIEW

**Comment by jcberquist** [comment]
Thanks, could you change the arrow function out for a regular function? I _claim_ to still support back to ACF 11, and I know the arrow function won't work on that version 😬 .

**Comment by zspitzer** [comment]
Sure, I just copied it from another function in the same file, shall I update that too?

**Comment by jcberquist** [comment]
Ha, good point! I should be more careful. Yes, if you would update that too, I would appreciate it.

**Comment by zspitzer** [comment]
done!

**Comment by jcberquist** [comment]
Thanks, very nice!

**Pull request merged**
