### PR TITLE
Add ability to proxy requests

### PR DESCRIPTION
**Pull request by barronbud**

### CODE REVIEW

**Comment by jcberquist** [comment]
Thank you for the pull request, I am sorry for the delay in getting to it. This looks good to me, but could we move from two arguments for the proxy config to a single one that is a struct? So:
```cfc
public struct function init(
        string awsKey = '',
        string awsSecretKey = '',
        string defaultRegion = '',
        struct constructorArgs = { },
        struct httpProxy = { server: '', port: 80 }
    ) {
```
I would also prefer if the port is specified as a number, rather than a string, since it is supposed to be a number. (I know that CFML will happily cast it, but I would still prefer it.)

I am not very familiar with using a proxy with CFHTTP - I presume that if the proxyserver attribute is included when using the cfhttp tag, but as an empty string, it then gets ignored?

**Comment by barronbud** [comment]
Good call - much cleaner that way.  It's been updated as requested.

For Lucee, the defaults look to be a blank string for proxyServer and 80 for the port...then if proxyServer is empty, it ignores it.  Not sure exactly how ACF handles it.  If you'd prefer, I can sniff out whether the defaults are set and construct the cfhttp call accordingly (if/else block).

**Comment by jcberquist** [comment]
Let's go with this for now, it looks to me like it works in both ACF and Lucee to pass an empty proxy server/port.

**Comment by jcberquist** [comment]
Thank you!

**Pull request merged**
